# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appearance_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class appreanceForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 680)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_16.setContentsMargins(80, 40, 80, 60)
        self.verticalLayout_16.setSpacing(20)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_theme = QtWidgets.QFrame(Form)
        self.frame_theme.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_theme.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_theme.setObjectName("frame_theme")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_theme)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_theme_0 = QtWidgets.QFrame(self.frame_theme)
        self.frame_theme_0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_theme_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_theme_0.setObjectName("frame_theme_0")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_theme_0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_theme0 = QtWidgets.QLabel(self.frame_theme_0)
        self.label_theme0.setObjectName("label_theme0")
        self.verticalLayout_2.addWidget(self.label_theme0)
        self.verticalLayout.addWidget(self.frame_theme_0)
        self.frame_theme_1 = QtWidgets.QFrame(self.frame_theme)
        self.frame_theme_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_theme_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_theme_1.setObjectName("frame_theme_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_theme_1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_theme_1_left = QtWidgets.QFrame(self.frame_theme_1)
        self.frame_theme_1_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_theme_1_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_theme_1_left.setObjectName("frame_theme_1_left")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_theme_1_left)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_theme1 = QtWidgets.QLabel(self.frame_theme_1_left)
        self.label_theme1.setObjectName("label_theme1")
        self.verticalLayout_4.addWidget(self.label_theme1)
        self.label_theme2 = QtWidgets.QLabel(self.frame_theme_1_left)
        self.label_theme2.setObjectName("label_theme2")
        self.verticalLayout_4.addWidget(self.label_theme2)
        self.label_theme3 = QtWidgets.QLabel(self.frame_theme_1_left)
        self.label_theme3.setObjectName("label_theme3")
        self.verticalLayout_4.addWidget(self.label_theme3)
        self.label_theme4 = QtWidgets.QLabel(self.frame_theme_1_left)
        self.label_theme4.setObjectName("label_theme4")
        self.verticalLayout_4.addWidget(self.label_theme4)
        self.horizontalLayout.addWidget(self.frame_theme_1_left)
        self.frame_theme_1_right = QtWidgets.QFrame(self.frame_theme_1)
        self.frame_theme_1_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_theme_1_right.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_theme_1_right.setObjectName("frame_theme_1_right")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_theme_1_right)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox_theme0 = QtWidgets.QComboBox(self.frame_theme_1_right)
        self.comboBox_theme0.setObjectName("comboBox_theme0")
        self.verticalLayout_3.addWidget(self.comboBox_theme0)
        self.comboBox_theme1 = QtWidgets.QComboBox(self.frame_theme_1_right)
        self.comboBox_theme1.setObjectName("comboBox_theme1")
        self.verticalLayout_3.addWidget(self.comboBox_theme1)
        self.comboBox_theme2 = QtWidgets.QComboBox(self.frame_theme_1_right)
        self.comboBox_theme2.setObjectName("comboBox_theme2")
        self.verticalLayout_3.addWidget(self.comboBox_theme2)
        self.comboBox_theme3 = QtWidgets.QComboBox(self.frame_theme_1_right)
        self.comboBox_theme3.setObjectName("comboBox_theme3")
        self.verticalLayout_3.addWidget(self.comboBox_theme3)
        self.horizontalLayout.addWidget(self.frame_theme_1_right)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.frame_theme_1)
        self.verticalLayout_16.addWidget(self.frame_theme)
        self.frame_background = QtWidgets.QFrame(Form)
        self.frame_background.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_background.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_background.setObjectName("frame_background")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_background)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_background0 = QtWidgets.QFrame(self.frame_background)
        self.frame_background0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_background0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_background0.setObjectName("frame_background0")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_background0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_background0 = QtWidgets.QLabel(self.frame_background0)
        self.label_background0.setObjectName("label_background0")
        self.verticalLayout_5.addWidget(self.label_background0)
        self.verticalLayout_8.addWidget(self.frame_background0)
        self.frame_background1 = QtWidgets.QFrame(self.frame_background)
        self.frame_background1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_background1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_background1.setObjectName("frame_background1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_background1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_background1_left = QtWidgets.QFrame(self.frame_background1)
        self.frame_background1_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_background1_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_background1_left.setObjectName("frame_background1_left")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_background1_left)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_background1 = QtWidgets.QLabel(self.frame_background1_left)
        self.label_background1.setObjectName("label_background1")
        self.verticalLayout_6.addWidget(self.label_background1)
        self.label_background2 = QtWidgets.QLabel(self.frame_background1_left)
        self.label_background2.setObjectName("label_background2")
        self.verticalLayout_6.addWidget(self.label_background2)
        self.horizontalLayout_2.addWidget(self.frame_background1_left)
        self.frame_background1_right = QtWidgets.QFrame(self.frame_background1)
        self.frame_background1_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_background1_right.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_background1_right.setObjectName("frame_background1_right")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_background1_right)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_background = QtWidgets.QLineEdit(self.frame_background1_right)
        self.lineEdit_background.setObjectName("lineEdit_background")
        self.verticalLayout_7.addWidget(self.lineEdit_background)
        self.comboBox_background = QtWidgets.QComboBox(self.frame_background1_right)
        self.comboBox_background.setObjectName("comboBox_background")
        self.verticalLayout_7.addWidget(self.comboBox_background)
        self.horizontalLayout_2.addWidget(self.frame_background1_right)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_8.addWidget(self.frame_background1)
        self.verticalLayout_16.addWidget(self.frame_background)
        self.frame_font = QtWidgets.QFrame(Form)
        self.frame_font.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_font.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_font.setObjectName("frame_font")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_font)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_font0 = QtWidgets.QLabel(self.frame_font)
        self.label_font0.setObjectName("label_font0")
        self.verticalLayout_15.addWidget(self.label_font0)
        self.frame_font1 = QtWidgets.QFrame(self.frame_font)
        self.frame_font1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_font1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_font1.setObjectName("frame_font1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_font1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.frame_font1)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_font1 = QtWidgets.QLabel(self.frame)
        self.label_font1.setObjectName("label_font1")
        self.verticalLayout_10.addWidget(self.label_font1)
        self.label_font2 = QtWidgets.QLabel(self.frame)
        self.label_font2.setObjectName("label_font2")
        self.verticalLayout_10.addWidget(self.label_font2)
        self.label_font3 = QtWidgets.QLabel(self.frame)
        self.label_font3.setObjectName("label_font3")
        self.verticalLayout_10.addWidget(self.label_font3)
        self.label_font4 = QtWidgets.QLabel(self.frame)
        self.label_font4.setObjectName("label_font4")
        self.verticalLayout_10.addWidget(self.label_font4)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_font1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_font0 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_font0.setDragEnabled(True)
        self.lineEdit_font0.setReadOnly(True)
        self.lineEdit_font0.setObjectName("lineEdit_font0")
        self.verticalLayout_9.addWidget(self.lineEdit_font0)
        self.lineEdit_font1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_font1.setDragEnabled(True)
        self.lineEdit_font1.setReadOnly(True)
        self.lineEdit_font1.setObjectName("lineEdit_font1")
        self.verticalLayout_9.addWidget(self.lineEdit_font1)
        self.lineEdit_font2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_font2.setReadOnly(True)
        self.lineEdit_font2.setObjectName("lineEdit_font2")
        self.verticalLayout_9.addWidget(self.lineEdit_font2)
        self.doubleSpinBox_font = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_font.setProperty("value", 1.0)
        self.doubleSpinBox_font.setObjectName("doubleSpinBox_font")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_font)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.verticalLayout_15.addWidget(self.frame_font1)
        self.frame_font2 = QtWidgets.QFrame(self.frame_font)
        self.frame_font2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_font2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_font2.setObjectName("frame_font2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_font2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 50, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_font2_0 = QtWidgets.QFrame(self.frame_font2)
        self.frame_font2_0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_font2_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_font2_0.setObjectName("frame_font2_0")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_font2_0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_font5 = QtWidgets.QLabel(self.frame_font2_0)
        self.label_font5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_font5.setObjectName("label_font5")
        self.horizontalLayout_3.addWidget(self.label_font5)
        self.horizontalLayout_4.addWidget(self.frame_font2_0)
        self.frame_font2_1 = QtWidgets.QFrame(self.frame_font2)
        self.frame_font2_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_font2_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_font2_1.setObjectName("frame_font2_1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_font2_1)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.radioButton_font_left0 = QtWidgets.QRadioButton(self.frame_font2_1)
        self.radioButton_font_left0.setObjectName("radioButton_font_left0")
        self.verticalLayout_14.addWidget(self.radioButton_font_left0)
        self.radioButton_font_left1 = QtWidgets.QRadioButton(self.frame_font2_1)
        self.radioButton_font_left1.setObjectName("radioButton_font_left1")
        self.verticalLayout_14.addWidget(self.radioButton_font_left1)
        self.radioButton_font_left2 = QtWidgets.QRadioButton(self.frame_font2_1)
        self.radioButton_font_left2.setObjectName("radioButton_font_left2")
        self.verticalLayout_14.addWidget(self.radioButton_font_left2)
        self.radioButton_font_left3 = QtWidgets.QRadioButton(self.frame_font2_1)
        self.radioButton_font_left3.setObjectName("radioButton_font_left3")
        self.verticalLayout_14.addWidget(self.radioButton_font_left3)
        self.horizontalLayout_4.addWidget(self.frame_font2_1)
        self.frame_font2_3 = QtWidgets.QFrame(self.frame_font2)
        self.frame_font2_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_font2_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_font2_3.setObjectName("frame_font2_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_font2_3)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_font6 = QtWidgets.QLabel(self.frame_font2_3)
        self.label_font6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_font6.setObjectName("label_font6")
        self.verticalLayout_12.addWidget(self.label_font6)
        self.horizontalLayout_4.addWidget(self.frame_font2_3)
        self.frame_font2_4 = QtWidgets.QFrame(self.frame_font2)
        self.frame_font2_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_font2_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_font2_4.setObjectName("frame_font2_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_font2_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_font_right0 = QtWidgets.QRadioButton(self.frame_font2_4)
        self.radioButton_font_right0.setObjectName("radioButton_font_right0")
        self.verticalLayout_13.addWidget(self.radioButton_font_right0)
        self.radioButton_font_right1 = QtWidgets.QRadioButton(self.frame_font2_4)
        self.radioButton_font_right1.setObjectName("radioButton_font_right1")
        self.verticalLayout_13.addWidget(self.radioButton_font_right1)
        self.radioButton_font_right2 = QtWidgets.QRadioButton(self.frame_font2_4)
        self.radioButton_font_right2.setObjectName("radioButton_font_right2")
        self.verticalLayout_13.addWidget(self.radioButton_font_right2)
        self.horizontalLayout_4.addWidget(self.frame_font2_4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout_15.addWidget(self.frame_font2)
        self.verticalLayout_16.addWidget(self.frame_font)
        self.verticalLayout_16.setStretch(0, 5)
        self.verticalLayout_16.setStretch(1, 3)
        self.verticalLayout_16.setStretch(2, 9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_theme0.setText(_translate("Form", "主题"))
        self.label_theme1.setText(_translate("Form", "应用程序"))
        self.label_theme2.setText(_translate("Form", "光标"))
        self.label_theme3.setText(_translate("Form", "图标"))
        self.label_theme4.setText(_translate("Form", "shell"))
        self.label_background0.setText(_translate("Form", "背景"))
        self.label_background1.setText(_translate("Form", "背景颜色"))
        self.label_background2.setText(_translate("Form", "调整"))
        self.label_font0.setText(_translate("Form", "字体"))
        self.label_font1.setText(_translate("Form", "窗口标题"))
        self.label_font2.setText(_translate("Form", "界面"))
        self.label_font3.setText(_translate("Form", "等宽"))
        self.label_font4.setText(_translate("Form", "缩放比例"))
        self.lineEdit_font0.setText(_translate("Form", "Segoe UI Bold  18"))
        self.lineEdit_font1.setText(_translate("Form", "Microsoft Yahei  9"))
        self.lineEdit_font2.setText(_translate("Form", "Ubuntu Regular  11"))
        self.label_font5.setText(_translate("Form", "微调"))
        self.radioButton_font_left0.setText(_translate("Form", "完全"))
        self.radioButton_font_left1.setText(_translate("Form", "中等"))
        self.radioButton_font_left2.setText(_translate("Form", "轻微"))
        self.radioButton_font_left3.setText(_translate("Form", "无"))
        self.label_font6.setText(_translate("Form", "抗锯齿"))
        self.radioButton_font_right0.setText(_translate("Form", "子像素(用于ＬＣＤ屏幕)"))
        self.radioButton_font_right1.setText(_translate("Form", "标准(灰度)"))
        self.radioButton_font_right2.setText(_translate("Form", "无"))
