# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class helpForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 680)
        Form.setMinimumSize(QtCore.QSize(800, 680))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 662))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_17.setContentsMargins(120, 30, 120, 30)
        self.verticalLayout_17.setSpacing(30)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_vision = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_vision.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_vision.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_vision.setObjectName("frame_vision")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_vision)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_0_0 = QtWidgets.QFrame(self.frame_vision)
        self.frame_0_0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_0_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_0_0.setObjectName("frame_0_0")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_0_0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_vision = QtWidgets.QLabel(self.frame_0_0)
        self.label_vision.setObjectName("label_vision")
        self.verticalLayout_4.addWidget(self.label_vision)
        self.verticalLayout_3.addWidget(self.frame_0_0)
        self.frame_0_1 = QtWidgets.QFrame(self.frame_vision)
        self.frame_0_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_0_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_0_1.setObjectName("frame_0_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_0_1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_0_1_left = QtWidgets.QFrame(self.frame_0_1)
        self.frame_0_1_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_0_1_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_0_1_left.setObjectName("frame_0_1_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_0_1_left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_highlight = QtWidgets.QLabel(self.frame_0_1_left)
        self.label_highlight.setIndent(30)
        self.label_highlight.setObjectName("label_highlight")
        self.verticalLayout_2.addWidget(self.label_highlight)
        self.label_bigtext = QtWidgets.QLabel(self.frame_0_1_left)
        self.label_bigtext.setIndent(30)
        self.label_bigtext.setObjectName("label_bigtext")
        self.verticalLayout_2.addWidget(self.label_bigtext)
        self.label_cursorsize = QtWidgets.QLabel(self.frame_0_1_left)
        self.label_cursorsize.setIndent(30)
        self.label_cursorsize.setObjectName("label_cursorsize")
        self.verticalLayout_2.addWidget(self.label_cursorsize)
        self.horizontalLayout.addWidget(self.frame_0_1_left)
        self.frame_0_1_right = QtWidgets.QFrame(self.frame_0_1)
        self.frame_0_1_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_0_1_right.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_0_1_right.setObjectName("frame_0_1_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_0_1_right)
        self.verticalLayout.setContentsMargins(0, 0, 30, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.switch_widget_highlight = QtWidgets.QWidget(self.frame_0_1_right)
        self.switch_widget_highlight.setObjectName("switch_widget_highlight")
        self.verticalLayout.addWidget(self.switch_widget_highlight)
        self.switch_widget_bigtext = QtWidgets.QWidget(self.frame_0_1_right)
        self.switch_widget_bigtext.setObjectName("switch_widget_bigtext")
        self.verticalLayout.addWidget(self.switch_widget_bigtext)
        self.switchwidget_cursorsize = QtWidgets.QWidget(self.frame_0_1_right)
        self.switchwidget_cursorsize.setObjectName("switchwidget_cursorsize")
        self.verticalLayout.addWidget(self.switchwidget_cursorsize)
        self.horizontalLayout.addWidget(self.frame_0_1_right)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame_0_1)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_17.addWidget(self.frame_vision)
        self.frame_warn = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_warn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_warn.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_warn.setObjectName("frame_warn")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_warn)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.frame_warn)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_warn1 = QtWidgets.QLabel(self.frame_2)
        self.label_warn1.setObjectName("label_warn1")
        self.verticalLayout_7.addWidget(self.label_warn1)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_warn)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_warn2 = QtWidgets.QLabel(self.frame_4)
        self.label_warn2.setIndent(30)
        self.label_warn2.setObjectName("label_warn2")
        self.horizontalLayout_2.addWidget(self.label_warn2)
        self.switch_widget_warn = QtWidgets.QWidget(self.frame_4)
        self.switch_widget_warn.setObjectName("switch_widget_warn")
        self.horizontalLayout_2.addWidget(self.switch_widget_warn)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(30, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_warn_left = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_warn_left.setObjectName("radioButton_warn_left")
        self.horizontalLayout_3.addWidget(self.radioButton_warn_left)
        self.radioButton_warn_right = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_warn_right.setObjectName("radioButton_warn_right")
        self.horizontalLayout_3.addWidget(self.radioButton_warn_right)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 2)
        self.verticalLayout_17.addWidget(self.frame_warn)
        self.frame_type = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_type.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_type.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_type.setObjectName("frame_type")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_type)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_7 = QtWidgets.QFrame(self.frame_type)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_type = QtWidgets.QLabel(self.frame_7)
        self.label_type.setObjectName("label_type")
        self.verticalLayout_9.addWidget(self.label_type)
        self.verticalLayout_12.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_type)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_type_left = QtWidgets.QFrame(self.frame_8)
        self.frame_type_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_type_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_type_left.setObjectName("frame_type_left")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_type_left)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_type_k = QtWidgets.QLabel(self.frame_type_left)
        self.label_type_k.setIndent(30)
        self.label_type_k.setObjectName("label_type_k")
        self.verticalLayout_11.addWidget(self.label_type_k)
        self.label_type_e = QtWidgets.QLabel(self.frame_type_left)
        self.label_type_e.setIndent(30)
        self.label_type_e.setObjectName("label_type_e")
        self.verticalLayout_11.addWidget(self.label_type_e)
        self.label_type_b = QtWidgets.QLabel(self.frame_type_left)
        self.label_type_b.setIndent(30)
        self.label_type_b.setObjectName("label_type_b")
        self.verticalLayout_11.addWidget(self.label_type_b)
        self.label_type_t = QtWidgets.QLabel(self.frame_type_left)
        self.label_type_t.setIndent(30)
        self.label_type_t.setObjectName("label_type_t")
        self.verticalLayout_11.addWidget(self.label_type_t)
        self.horizontalLayout_4.addWidget(self.frame_type_left)
        self.frame_type_right = QtWidgets.QFrame(self.frame_8)
        self.frame_type_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_type_right.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_type_right.setObjectName("frame_type_right")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_type_right)
        self.verticalLayout_10.setContentsMargins(0, 0, 30, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.switch_widget_k = QtWidgets.QWidget(self.frame_type_right)
        self.switch_widget_k.setObjectName("switch_widget_k")
        self.verticalLayout_10.addWidget(self.switch_widget_k)
        self.switch_widget_e = QtWidgets.QWidget(self.frame_type_right)
        self.switch_widget_e.setObjectName("switch_widget_e")
        self.verticalLayout_10.addWidget(self.switch_widget_e)
        self.switch_widget_b = QtWidgets.QWidget(self.frame_type_right)
        self.switch_widget_b.setObjectName("switch_widget_b")
        self.verticalLayout_10.addWidget(self.switch_widget_b)
        self.switch_widget_4 = QtWidgets.QWidget(self.frame_type_right)
        self.switch_widget_4.setObjectName("switch_widget_4")
        self.verticalLayout_10.addWidget(self.switch_widget_4)
        self.horizontalLayout_4.addWidget(self.frame_type_right)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 4)
        self.verticalLayout_17.addWidget(self.frame_type)
        self.frame_point = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_point.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_point.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_point.setObjectName("frame_point")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_point)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame = QtWidgets.QFrame(self.frame_point)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_point = QtWidgets.QLabel(self.frame)
        self.label_point.setObjectName("label_point")
        self.verticalLayout_15.addWidget(self.label_point)
        self.verticalLayout_16.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.frame_point)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_point_m = QtWidgets.QLabel(self.frame_9)
        self.label_point_m.setIndent(30)
        self.label_point_m.setObjectName("label_point_m")
        self.verticalLayout_14.addWidget(self.label_point_m)
        self.label_point_c = QtWidgets.QLabel(self.frame_9)
        self.label_point_c.setIndent(30)
        self.label_point_c.setObjectName("label_point_c")
        self.verticalLayout_14.addWidget(self.label_point_c)
        self.gridLayout.addWidget(self.frame_9, 0, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_13.setContentsMargins(0, 0, 30, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.switch_widget_m = QtWidgets.QWidget(self.frame_10)
        self.switch_widget_m.setObjectName("switch_widget_m")
        self.verticalLayout_13.addWidget(self.switch_widget_m)
        self.switch_widget_c = QtWidgets.QWidget(self.frame_10)
        self.switch_widget_c.setObjectName("switch_widget_c")
        self.verticalLayout_13.addWidget(self.switch_widget_c)
        self.gridLayout.addWidget(self.frame_10, 0, 1, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setContentsMargins(0, 10, 30, 0)
        self.horizontalLayout_5.setSpacing(30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_point_d = QtWidgets.QLabel(self.frame_11)
        self.label_point_d.setIndent(30)
        self.label_point_d.setObjectName("label_point_d")
        self.horizontalLayout_5.addWidget(self.label_point_d)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider.setProperty("value", 36)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_5.addWidget(self.horizontalSlider)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 4)
        self.gridLayout.addWidget(self.frame_11, 1, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 1)
        self.verticalLayout_16.addWidget(self.frame_6)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 3)
        self.verticalLayout_17.addWidget(self.frame_point)
        self.verticalLayout_17.setStretch(0, 4)
        self.verticalLayout_17.setStretch(1, 3)
        self.verticalLayout_17.setStretch(2, 5)
        self.verticalLayout_17.setStretch(3, 4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_vision.setText(_translate("Form", "视觉"))
        self.label_highlight.setText(_translate("Form", "高对比度(H)"))
        self.label_bigtext.setText(_translate("Form", "大号文本(L)"))
        self.label_cursorsize.setText(_translate("Form", "光标大小(U)"))
        self.label_warn1.setText(_translate("Form", "视觉警告"))
        self.label_warn2.setText(_translate("Form", "发出警告时使用视觉提示(V)"))
        self.radioButton_warn_left.setText(_translate("Form", "闪烁窗口标题栏(W)"))
        self.radioButton_warn_right.setText(_translate("Form", "闪烁整个屏幕(S)"))
        self.label_type.setText(_translate("Form", "打字"))
        self.label_type_k.setText(_translate("Form", "屏幕键盘(K)"))
        self.label_type_e.setText(_translate("Form", "重复键(E)"))
        self.label_type_b.setText(_translate("Form", "光标闪烁(B)"))
        self.label_type_t.setText(_translate("Form", "AccessX打字助手(T)"))
        self.label_point.setText(_translate("Form", "指向和点击"))
        self.label_point_m.setText(_translate("Form", "鼠标键(M)"))
        self.label_point_c.setText(_translate("Form", "点击助手(C)"))
        self.label_point_d.setText(_translate("Form", "双向延时(D)"))
