# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osvos_Form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore,QtWidgets
from PyQt5.QtWidgets import QLabel
from PyQt5.QtCore import Qt

class MyLabel_Mask(QLabel):
    openMaskSignal = QtCore.pyqtSignal()  # 信号
    def __init__(self, parent=None):
        super(MyLabel_Mask, self).__init__((parent))

    def mouseDoubleClickEvent(self, event):
        QLabel.mouseDoubleClickEvent(self, event)
        self.openMaskSignal.emit()


class osvos_form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 2, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        # self.commandLinkButton_return = QtWidgets.QCommandLinkButton(self.frame)
        # self.commandLinkButton_return.setObjectName("commandLinkButton_return")
        # self.horizontalLayout_6.addWidget(self.commandLinkButton_return)

        self.pushButton_return = QtWidgets.QPushButton(self.frame)
        self.pushButton_return.setFocusPolicy(Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_return.sizePolicy().hasHeightForWidth())
        self.pushButton_return.setSizePolicy(sizePolicy)
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayout_6.addWidget(self.pushButton_return)

        self.label_title = QtWidgets.QLabel(self.frame)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_6.addWidget(self.label_title)

        # self.frame_10 = QtWidgets.QFrame(self.frame)
        # self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        # self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        # self.frame_10.setObjectName("frame_10")
        # self.horizontalLayout_6.addWidget(self.frame_10)
        # self.commandLinkButton_next = QtWidgets.QCommandLinkButton(self.frame)
        # self.commandLinkButton_next.setObjectName("commandLinkButton_next")
        # self.horizontalLayout_6.addWidget(self.commandLinkButton_next)
        self.pushButton_next = QtWidgets.QPushButton(self.frame)
        self.pushButton_next.setFocusPolicy(Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next.sizePolicy().hasHeightForWidth())
        self.pushButton_next.setSizePolicy(sizePolicy)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_6.addWidget(self.pushButton_next)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2_1 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2_1.setObjectName("frame_2_1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2_1)
        self.horizontalLayout_4.setContentsMargins(1, 1, 2, 2)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        # self.label=QtWidgets.QLabel(self.frame_2_1)
        # self.label.setAlignment(QtCore.Qt.AlignHCenter| QtCore.Qt.AlignVCenter)
        # self.label.setObjectName("label")
        # self.horizontalLayout_4.addWidget(self.label)
        # self.spinbox=QtWidgets.QSpinBox(self.frame_2_1)
        # self.spinbox.setRange(0,500)
        # self.spinbox.setSingleStep(10)
        # self.spinbox.setValue(50)
        # self.horizontalLayout_4.addWidget(self.spinbox)

        # 选择快速还是慢速模型
        self.comboBox_model = QtWidgets.QComboBox(self.frame_2_1)
        self.comboBox_model.setObjectName("comboBox_model")
        self.horizontalLayout_4.addWidget(self.comboBox_model)
        self.comboBox_model.setFocusPolicy(Qt.NoFocus)
        self.pushButton_left0 = QtWidgets.QPushButton(self.frame_2_1)
        self.pushButton_left0.setObjectName("pushButton_left0")
        self.horizontalLayout_4.addWidget(self.pushButton_left0)
        self.pushButton_left1 = QtWidgets.QPushButton(self.frame_2_1)
        self.pushButton_left1.setObjectName("pushButton_left1")
        self.horizontalLayout_4.addWidget(self.pushButton_left1)
        # self.pushButton_left2 = QtWidgets.QPushButton(self.frame_2_1)
        # self.pushButton_left2.setObjectName("pushButton_left2")
        # self.horizontalLayout_4.addWidget(self.pushButton_left2)
        # self.pushButton_left3 = QtWidgets.QPushButton(self.frame_2_1)
        # self.pushButton_left3.setObjectName("pushButton_left3")
        # self.horizontalLayout_4.addWidget(self.pushButton_left3)
        # self.pushButton_left4 = QtWidgets.QPushButton(self.frame_2_1)
        # self.pushButton_left4.setObjectName("pushButton_left4")
        # self.horizontalLayout_4.addWidget(self.pushButton_left4)
        self.pushButton_left5 = QtWidgets.QPushButton(self.frame_2_1)
        self.pushButton_left5.setObjectName("pushButton_left5")
        self.horizontalLayout_4.addWidget(self.pushButton_left5)
        self.pushButton_left6 = QtWidgets.QPushButton(self.frame_2_1)
        self.pushButton_left6.setObjectName("pushButton_left6")
        self.horizontalLayout_4.addWidget(self.pushButton_left6)
        self.pushButton_left0.setFocusPolicy(Qt.NoFocus)
        self.pushButton_left1.setFocusPolicy(Qt.NoFocus)
        self.pushButton_left5.setFocusPolicy(Qt.NoFocus)
        self.pushButton_left6.setFocusPolicy(Qt.NoFocus)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 2)

        self.verticalLayout_2.addWidget(self.frame_2_1)
        self.leftImage = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftImage.sizePolicy().hasHeightForWidth())
        self.leftImage.setSizePolicy(sizePolicy)
        self.leftImage.setText("")
        self.leftImage.setObjectName("leftImage")
        self.leftImage.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_2.addWidget(self.leftImage)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider_left = QtWidgets.QSlider(self.frame_6)
        self.horizontalSlider_left.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_left.setObjectName("horizontalSlider_left")
        self.horizontalSlider_left.setFocusPolicy(Qt.NoFocus)
        self.gridLayout.addWidget(self.horizontalSlider_left, 0, 0, 1, 3)
        self.label_time1 = QtWidgets.QLabel(self.frame_6)
        self.label_time1.setObjectName("label_time1")
        self.gridLayout.addWidget(self.label_time1, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout.addWidget(self.frame_7, 1, 1, 1, 1)
        self.label_time2 = QtWidgets.QLabel(self.frame_6)
        self.label_time2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time2.setObjectName("label_time2")
        self.gridLayout.addWidget(self.label_time2, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 4)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 3)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.dockWidget = QtWidgets.QDockWidget(self.frame_2)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_right1 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_right1.setObjectName("pushButton_right1")
        self.horizontalLayout_5.addWidget(self.pushButton_right1)
        self.pushButton_right2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_right2.setObjectName("pushButton_right2")
        self.horizontalLayout_5.addWidget(self.pushButton_right2)
        self.pushButton_right3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_right3.setObjectName("pushButton_right3")
        self.horizontalLayout_5.addWidget(self.pushButton_right3)
        self.pushButton_right1.setFocusPolicy(Qt.NoFocus)
        self.pushButton_right2.setFocusPolicy(Qt.NoFocus)
        self.pushButton_right3.setFocusPolicy(Qt.NoFocus)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.rightImage = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightImage.sizePolicy().hasHeightForWidth())
        self.rightImage.setSizePolicy(sizePolicy)
        self.rightImage.setText("")
        self.rightImage.setObjectName("rightImage")
        self.rightImage.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_3.addWidget(self.rightImage)
        self.frame_8 = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalSlider_right = QtWidgets.QSlider(self.frame_8)
        self.horizontalSlider_right.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_right.setObjectName("horizontalSlider_right")
        self.horizontalSlider_right.setFocusPolicy(Qt.NoFocus)
        self.gridLayout_2.addWidget(self.horizontalSlider_right, 0, 0, 1, 3)
        self.label_time3 = QtWidgets.QLabel(self.frame_8)
        self.label_time3.setObjectName("label_time3")
        self.gridLayout_2.addWidget(self.label_time3, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_2.addWidget(self.frame_9, 1, 1, 1, 1)
        self.label_time4 = QtWidgets.QLabel(self.frame_8)
        self.label_time4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time4.setObjectName("label_time4")
        self.gridLayout_2.addWidget(self.label_time4, 1, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 6)
        self.verticalLayout_3.setStretch(2, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout_2.addWidget(self.dockWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_mask = MyLabel_Mask(self.frame_5)
        self.label_mask.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_mask.setText("")
        self.label_mask.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mask.setObjectName("label_mask")
        self.horizontalLayout_7.addWidget(self.label_mask)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addWidget(self.frame_3)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setTextVisible(False)#不显示进度条上的文本
        self.progressBar.setMaximum(1)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(3, 5)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.comboBox_model.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", " "))
        self.groupBox.setTitle(_translate("Form", ""))
        # self.commandLinkButton_return.setText(_translate("Form", "Return"))
        # self.commandLinkButton_next.setText(_translate("Form", "Next"))
        self.pushButton_return.setText(_translate("Form", "Return"))
        self.pushButton_next.setText(_translate("Form", "Next"))
        #self.label.setText(_translate("Form", "选择迭代次数"))
        self.pushButton_left0.setText(_translate("Form", "Annotate Object"))
        self.pushButton_left1.setText(_translate("Form", "Start Segmentate"))
        # self.pushButton_left2.setText(_translate("Form", "Stop Finetune"))
        # self.pushButton_left3.setText(_translate("Form", "Start Test"))
        # self.pushButton_left4.setText(_translate("Form", "Stop Test"))
        self.pushButton_left5.setText(_translate("Form", "Start Play"))
        self.pushButton_left6.setText(_translate("Form", "Pause Play"))
        self.label_time1.setText(_translate("Form", "00:00:00"))
        self.label_time2.setText(_translate("Form", "00:00:00"))
        self.pushButton_right1.setText(_translate("Form", "Open Video"))
        self.pushButton_right2.setText(_translate("Form", "Start Play"))
        self.pushButton_right3.setText(_translate("Form", "Pause Play"))
        self.label_time3.setText(_translate("Form", "00:00:00"))
        self.label_time4.setText(_translate("Form", "00:00:00"))
        self.label_title.setText(_translate("Form", "Osvos & RGMP"))
