# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workzone_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel


class MyLabel(QLabel):
    chooseSignal = QtCore.pyqtSignal()  # 信号
    def __init__(self, parent=None):
        super(MyLabel, self).__init__((parent))

    def mouseDoubleClickEvent(self, event):
        QLabel.mouseDoubleClickEvent(self, event)

    def mousePressEvent(self, event):
        QLabel.mousePressEvent(self, event)
        self.chooseSignal.emit()

    def mouseReleaseEvent(self, event):
        QLabel.mouseReleaseEvent(self, event)

class Ui_workzone_form(object):
    def setupUi(self, workzone_form):
        workzone_form.setObjectName("workzone_form")
        workzone_form.resize(800, 680)
        self.verticalLayout = QtWidgets.QVBoxLayout(workzone_form)
        self.verticalLayout.setContentsMargins(50, 40, 50, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_0 = QtWidgets.QFrame(workzone_form)
        self.frame_0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_0.setObjectName("frame_0")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_static = QtWidgets.QFrame(self.frame_0)
        self.frame_static.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_static.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_static.setObjectName("frame_static")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_static)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_static_left = QtWidgets.QFrame(self.frame_static)
        self.frame_static_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_static_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_static_left.setObjectName("frame_static_left")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_static_left)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_staitc1 = MyLabel(self.frame_static_left)
        self.label_staitc1.setObjectName("label_staitc1")
        self.verticalLayout_5.addWidget(self.label_staitc1)
        self.label_static2 = MyLabel(self.frame_static_left)
        self.label_static2.setObjectName("label_static2")
        self.verticalLayout_5.addWidget(self.label_static2)
        self.horizontalLayout_3.addWidget(self.frame_static_left)
        self.frame_static_right = QtWidgets.QFrame(self.frame_static)
        self.frame_static_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_static_right.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_static_right.setObjectName("frame_static_right")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_static_right)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_static_icon = MyLabel(self.frame_static_right)
        self.label_static_icon.setText("")
        self.label_static_icon.setObjectName("label_static_icon")
        self.verticalLayout_8.addWidget(self.label_static_icon)
        self.horizontalLayout_3.addWidget(self.frame_static_right)
        self.horizontalLayout_3.setStretch(0, 8)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_9.addWidget(self.frame_static)
        self.frame_dynamic = QtWidgets.QFrame(self.frame_0)
        self.frame_dynamic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_dynamic.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_dynamic.setObjectName("frame_dynamic")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_dynamic)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_dynamic_left = QtWidgets.QFrame(self.frame_dynamic)
        self.frame_dynamic_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_dynamic_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_dynamic_left.setObjectName("frame_dynamic_left")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_dynamic_left)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_dynamic1 = MyLabel(self.frame_dynamic_left)
        self.label_dynamic1.setObjectName("label_dynamic1")
        self.verticalLayout_6.addWidget(self.label_dynamic1)
        self.label_dynamic2 = MyLabel(self.frame_dynamic_left)
        self.label_dynamic2.setObjectName("label_dynamic2")
        self.verticalLayout_6.addWidget(self.label_dynamic2)
        self.horizontalLayout_4.addWidget(self.frame_dynamic_left)
        self.frame_dynamic_right = QtWidgets.QFrame(self.frame_dynamic)
        self.frame_dynamic_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_dynamic_right.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_dynamic_right.setObjectName("frame_dynamic_right")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_dynamic_right)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_dynamic_icon = MyLabel(self.frame_dynamic_right)
        self.label_dynamic_icon.setText("")
        self.label_dynamic_icon.setObjectName("label_dynamic_icon")
        self.verticalLayout_7.addWidget(self.label_dynamic_icon)
        self.horizontalLayout_4.addWidget(self.frame_dynamic_right)
        self.horizontalLayout_4.setStretch(0, 8)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_9.addWidget(self.frame_dynamic)
        self.frame_5 = QtWidgets.QFrame(self.frame_0)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_worknum = MyLabel(self.frame_5)
        self.label_worknum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_worknum.setObjectName("label_worknum")
        self.horizontalLayout.addWidget(self.label_worknum)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout.addWidget(self.frame_6)
        self.spinBox_worknum = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox_worknum.setMinimum(1)
        self.spinBox_worknum.setMaximum(5)
        self.spinBox_worknum.setObjectName("spinBox_worknum")
        self.horizontalLayout.addWidget(self.spinBox_worknum)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.verticalLayout_9.setStretch(0, 2)
        self.verticalLayout_9.setStretch(1, 2)
        self.verticalLayout_9.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_0)
        self.frame_1 = QtWidgets.QFrame(workzone_form)
        self.frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_4.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_set = MyLabel(self.frame_1)
        self.label_set.setObjectName("label_set")
        self.verticalLayout_4.addWidget(self.label_set)
        self.frame_1_0 = QtWidgets.QFrame(self.frame_1)
        self.frame_1_0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1_0.setObjectName("frame_1_0")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_1_0)
        self.horizontalLayout_2.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_resize = QtWidgets.QFrame(self.frame_1_0)
        self.frame_resize.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_resize.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_resize.setObjectName("frame_resize")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_resize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_resize = MyLabel(self.frame_resize)
        self.label_resize.setObjectName("label_resize")
        self.verticalLayout_3.addWidget(self.label_resize)
        self.label_drag = MyLabel(self.frame_resize)
        self.label_drag.setObjectName("label_drag")
        self.verticalLayout_3.addWidget(self.label_drag)
        self.horizontalLayout_2.addWidget(self.frame_resize)
        self.frame_drag = QtWidgets.QFrame(self.frame_1_0)
        self.frame_drag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_drag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_drag.setObjectName("frame_drag")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_drag)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_resize_icon = MyLabel(self.frame_drag)
        self.label_resize_icon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_resize_icon.setText("")
        self.label_resize_icon.setObjectName("label_resize_icon")
        self.verticalLayout_2.addWidget(self.label_resize_icon)
        self.label_drag_icon = MyLabel(self.frame_drag)
        self.label_drag_icon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_drag_icon.setText("")
        self.label_drag_icon.setObjectName("label_drag_icon")
        self.verticalLayout_2.addWidget(self.label_drag_icon)
        self.horizontalLayout_2.addWidget(self.frame_drag)
        self.horizontalLayout_2.setStretch(0, 8)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_1_0)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 5)
        self.verticalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(workzone_form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 3)

        self.retranslateUi(workzone_form)
        QtCore.QMetaObject.connectSlotsByName(workzone_form)

    def retranslateUi(self, workzone_form):
        _translate = QtCore.QCoreApplication.translate
        workzone_form.setWindowTitle(_translate("workzone_form", "Form"))
        self.label_staitc1.setText(_translate("workzone_form", "静态工作区"))
        self.label_static2.setText(_translate("workzone_form", "工作区的数量固定．"))
        self.label_dynamic2.setText(_translate("workzone_form", "工作区可以按需创建，并在其为空时自动移除．"))
        self.label_dynamic1.setText(_translate("workzone_form", "动态工作区"))
        self.label_worknum.setText(_translate("workzone_form", "工作区数量"))
        self.label_set.setText(_translate("workzone_form", "工作区显示设置"))
        self.label_resize.setText(_translate("workzone_form", "允许工作区窗口缩放"))
        self.label_drag.setText(_translate("workzone_form", "允许工作区窗口拖动"))