@startuml

title __IMGCODECS's Class Diagram__\n

  namespace org.opencv {
    namespace imgcodecs {
      class org.opencv.imgcodecs.Imgcodecs {
          {static} + IMREAD_ANYCOLOR : int
          {static} + IMREAD_ANYDEPTH : int
          {static} + IMREAD_COLOR : int
          {static} + IMREAD_GRAYSCALE : int
          {static} + IMREAD_IGNORE_ORIENTATION : int
          {static} + IMREAD_LOAD_GDAL : int
          {static} + IMREAD_REDUCED_COLOR_2 : int
          {static} + IMREAD_REDUCED_COLOR_4 : int
          {static} + IMREAD_REDUCED_COLOR_8 : int
          {static} + IMREAD_REDUCED_GRAYSCALE_2 : int
          {static} + IMREAD_REDUCED_GRAYSCALE_4 : int
          {static} + IMREAD_REDUCED_GRAYSCALE_8 : int
          {static} + IMREAD_UNCHANGED : int
          {static} + IMWRITE_EXR_TYPE : int
          {static} + IMWRITE_EXR_TYPE_FLOAT : int
          {static} + IMWRITE_EXR_TYPE_HALF : int
          {static} + IMWRITE_JPEG2000_COMPRESSION_X1000 : int
          {static} + IMWRITE_JPEG_CHROMA_QUALITY : int
          {static} + IMWRITE_JPEG_LUMA_QUALITY : int
          {static} + IMWRITE_JPEG_OPTIMIZE : int
          {static} + IMWRITE_JPEG_PROGRESSIVE : int
          {static} + IMWRITE_JPEG_QUALITY : int
          {static} + IMWRITE_JPEG_RST_INTERVAL : int
          {static} + IMWRITE_PAM_FORMAT_BLACKANDWHITE : int
          {static} + IMWRITE_PAM_FORMAT_GRAYSCALE : int
          {static} + IMWRITE_PAM_FORMAT_GRAYSCALE_ALPHA : int
          {static} + IMWRITE_PAM_FORMAT_NULL : int
          {static} + IMWRITE_PAM_FORMAT_RGB : int
          {static} + IMWRITE_PAM_FORMAT_RGB_ALPHA : int
          {static} + IMWRITE_PAM_TUPLETYPE : int
          {static} + IMWRITE_PNG_BILEVEL : int
          {static} + IMWRITE_PNG_COMPRESSION : int
          {static} + IMWRITE_PNG_STRATEGY : int
          {static} + IMWRITE_PNG_STRATEGY_DEFAULT : int
          {static} + IMWRITE_PNG_STRATEGY_FILTERED : int
          {static} + IMWRITE_PNG_STRATEGY_FIXED : int
          {static} + IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY : int
          {static} + IMWRITE_PNG_STRATEGY_RLE : int
          {static} + IMWRITE_PXM_BINARY : int
          {static} + IMWRITE_TIFF_COMPRESSION : int
          {static} + IMWRITE_TIFF_RESUNIT : int
          {static} + IMWRITE_TIFF_XDPI : int
          {static} + IMWRITE_TIFF_YDPI : int
          {static} + IMWRITE_WEBP_QUALITY : int
          {static} + haveImageReader()
          {static} + haveImageWriter()
          {static} + imdecode()
          {static} + imencode()
          {static} + imencode()
          {static} + imread()
          {static} + imread()
          {static} + imreadmulti()
          {static} + imreadmulti()
          {static} + imwrite()
          {static} + imwrite()
          {static} - haveImageReader_0()
          {static} - haveImageWriter_0()
          {static} - imdecode_0()
          {static} - imencode_0()
          {static} - imencode_1()
          {static} - imread_0()
          {static} - imread_1()
          {static} - imreadmulti_0()
          {static} - imreadmulti_1()
          {static} - imwrite_0()
          {static} - imwrite_1()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
