@startuml

title __UTILS's Class Diagram__\n

  namespace org.opencv {
    namespace utils {
      class org.opencv.utils.Converters {
          {static} + Mat_to_vector_DMatch()
          {static} + Mat_to_vector_KeyPoint()
          {static} + Mat_to_vector_Mat()
          {static} + Mat_to_vector_Point()
          {static} + Mat_to_vector_Point2d()
          {static} + Mat_to_vector_Point2f()
          {static} + Mat_to_vector_Point3()
          {static} + Mat_to_vector_Point3d()
          {static} + Mat_to_vector_Point3f()
          {static} + Mat_to_vector_Point3i()
          {static} + Mat_to_vector_Rect()
          {static} + Mat_to_vector_Rect2d()
          {static} + Mat_to_vector_RotatedRect()
          {static} + Mat_to_vector_char()
          {static} + Mat_to_vector_double()
          {static} + Mat_to_vector_float()
          {static} + Mat_to_vector_int()
          {static} + Mat_to_vector_uchar()
          {static} + Mat_to_vector_vector_DMatch()
          {static} + Mat_to_vector_vector_KeyPoint()
          {static} + Mat_to_vector_vector_Point()
          {static} + Mat_to_vector_vector_Point2f()
          {static} + Mat_to_vector_vector_Point3f()
          {static} + Mat_to_vector_vector_char()
          {static} + vector_DMatch_to_Mat()
          {static} + vector_KeyPoint_to_Mat()
          {static} + vector_Mat_to_Mat()
          {static} + vector_Point2d_to_Mat()
          {static} + vector_Point2f_to_Mat()
          {static} + vector_Point3_to_Mat()
          {static} + vector_Point3d_to_Mat()
          {static} + vector_Point3f_to_Mat()
          {static} + vector_Point3i_to_Mat()
          {static} + vector_Point_to_Mat()
          {static} + vector_Point_to_Mat()
          {static} + vector_Rect2d_to_Mat()
          {static} + vector_Rect_to_Mat()
          {static} + vector_RotatedRect_to_Mat()
          {static} + vector_char_to_Mat()
          {static} + vector_double_to_Mat()
          {static} + vector_float_to_Mat()
          {static} + vector_int_to_Mat()
          {static} + vector_uchar_to_Mat()
          {static} + vector_vector_DMatch_to_Mat()
          {static} + vector_vector_KeyPoint_to_Mat()
          {static} + vector_vector_Point2f_to_Mat()
          {static} + vector_vector_Point3f_to_Mat()
          {static} + vector_vector_Point_to_Mat()
          {static} + vector_vector_char_to_Mat()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
